In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as s

In [2]:
data = pd.read_csv("data.csv")

In [3]:
data

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [4]:
data.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave points_mean', 'symmetry_mean', 'fractal_dimension_mean',
       'radius_se', 'texture_se', 'perimeter_se', 'area_se', 'smoothness_se',
       'compactness_se', 'concavity_se', 'concave points_se', 'symmetry_se',
       'fractal_dimension_se', 'radius_worst', 'texture_worst',
       'perimeter_worst', 'area_worst', 'smoothness_worst',
       'compactness_worst', 'concavity_worst', 'concave points_worst',
       'symmetry_worst', 'fractal_dimension_worst', 'Unnamed: 32'],
      dtype='object')

In [5]:
data.drop([data.columns[0],data.columns[32]],axis=1,inplace=True)

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   diagnosis                569 non-null    object 
 1   radius_mean              569 non-null    float64
 2   texture_mean             569 non-null    float64
 3   perimeter_mean           569 non-null    float64
 4   area_mean                569 non-null    float64
 5   smoothness_mean          569 non-null    float64
 6   compactness_mean         569 non-null    float64
 7   concavity_mean           569 non-null    float64
 8   concave points_mean      569 non-null    float64
 9   symmetry_mean            569 non-null    float64
 10  fractal_dimension_mean   569 non-null    float64
 11  radius_se                569 non-null    float64
 12  texture_se               569 non-null    float64
 13  perimeter_se             569 non-null    float64
 14  area_se                  5

In [7]:
labels = np.array(data['diagnosis']).reshape(data['diagnosis'].shape[0],1)

In [8]:
X = np.array(data.iloc[:,1:])

In [9]:
mu = np.mean(X,axis=0)

In [10]:
mu.shape

(30,)

In [11]:
mu = mu.reshape(-1,mu.shape[0])

In [12]:
mu.shape

(1, 30)

In [13]:
X_dash = X - mu

In [14]:
X_dash.shape

(569, 30)

In [15]:
X.shape

(569, 30)

In [16]:
sigma_hat = (1/data.shape[0])*np.matmul(X_dash.T,X_dash)

In [17]:
sigma_hat.shape

(30, 30)

In [18]:
sigma_hat_decompose = np.linalg.svd(sigma_hat)

In [19]:
sigma_hat_decompose[1].shape

(30,)

In [20]:
lmbda = sigma_hat_decompose[1]
lmbda

array([4.43002671e+05, 7.29725279e+03, 7.02596776e+02, 5.45526944e+01,
       3.98199123e+01, 2.99930721e+00, 1.81213991e+00, 3.70813899e-01,
       1.55240237e-01, 8.39134846e-02, 3.15534015e-02, 7.48418875e-03,
       3.15610001e-03, 2.15770517e-03, 1.32420744e-03, 6.39144051e-04,
       3.74224474e-04, 2.34756323e-04, 1.84259067e-04, 1.63891523e-04,
       7.79729248e-05, 5.75099161e-05, 3.48559114e-05, 2.83453651e-05,
       1.61179909e-05, 1.24682907e-05, 3.67401338e-06, 2.84289915e-06,
       2.00139207e-06, 7.00763523e-07])

In [21]:
Q = sigma_hat_decompose[0]

In [22]:
Q_tilda = Q[:,0:15]

In [23]:
Q_tilda.shape

(30, 15)

In [24]:
X_new = np.matmul(X_dash,Q_tilda)

In [25]:
X_new.shape

(569, 15)

In [26]:
data.shape

(569, 31)

In [27]:
new_data = pd.DataFrame(X_new)

In [28]:
labels = labels.ravel()

In [29]:
new_data['diagnosis'] = labels

In [30]:
new_data

0           1          2          3          4         5  \
0   -1160.142574 -293.917544  48.578398   8.711975  32.000486 -1.265415   
1   -1269.122443   15.630182 -35.394534 -17.861283  -4.334874  0.225872   
2    -995.793889   39.156743  -1.709753  -4.199340  -0.466529  2.652811   
3     407.180803  -67.380320   8.672848  11.759867   7.115461 -1.299436   
4    -930.341180  189.340742   1.374801  -8.499183   7.613289 -1.021160   
..           ...         ...        ...        ...        ...       ...   
564 -1414.126684  110.222492  40.065944  -6.562240  -5.102856  0.395424   
565 -1045.018854   77.057589   0.036669   4.753245 -12.417863  0.059637   
566  -314.501756   47.553525 -10.442407   9.771881  -6.156213  0.870726   
567 -1124.858115   34.129225 -19.742087  23.660881   3.565133 -4.086390   
568   771.527622  -88.643106  23.889032  -2.547249 -14.717566 -4.418123   

            6         7         8         9        10        11        12  \
0    0.931337 -0.148167 -0.745463  0.589359  0.307804 -0.043452  0.034777   
1   -0.046037 -0.200804  0.485828 -0.084035 -0.080642 -0.033042  0.045485   
2   -0.779745  0.274026  0.173874 -0.186994 -0.279174  0.020464  0.083505   
3   -1.267304  0.060555  0.330639 -0.144155 -0.927471  0.174720  0.282556   
4   -0.335522 -0.289109 -0.036087 -0.138502 -0.042228  0.062721 -0.114247   
..        ...       ...       ...       ...       ...       ...       ...   
564 -0.786751 -0.037082  0.452530 -0.235185 -0.163649 -0.052543 -0.075032   
565  0.449831 -0.509154  0.449986  0.493247 -0.007625 -0.055832 -0.015163   
566 -2.166493  0.442279  0.097398 -0.144667  0.109147 -0.076263 -0.004448   
567 -1.705401  0.359964 -0.385030  0.615467 -0.307166  0.028224  0.060561   
568 -2.815752 -0.030039  0.423451 -0.301439 -0.133353  0.115105 -0.019667   

           13        14 diagnosis  
0   -0.065069  0.012934         M  
1    0.005534 -0.021368         M  
2   -0.024824  0.026887         M  
3   -0.080057 -0.043201         M  
4   -0.002274  0.019548         M  
..        ...       ...       ...  
564  0.015211  0.061390         M  
565 -0.009985 -0.003312         M  
566  0.055285  0.012459         M  
567  0.037742  0.031873         M  
568 -0.013734  0.004134         B  

[569 rows x 16 columns]

In [31]:
new_data[new_data['diagnosis']  == 'M'].shape

(212, 16)

In [32]:
new_data[new_data['diagnosis']  == 'B'].shape

(357, 16)

In [33]:
training_data_len = int(0.7*new_data.shape[0])

In [34]:
benign_traning_data =  new_data[new_data['diagnosis']  == 'B'].iloc[0:training_data_len//2]
malignant_traning_data = new_data[new_data['diagnosis'] == 'M'].iloc[0:training_data_len//2]

In [35]:
benign_traning_data.shape

(199, 16)

In [36]:
malignant_traning_data.shape

(199, 16)

In [37]:
training_data = pd.concat([benign_traning_data,malignant_traning_data])

In [38]:
training_data

0           1          2          3         4         5  \
19    191.621045   12.259178  -6.241020  -3.588034  6.692721  0.037497   
20    285.051275   14.557362 -10.177971  -1.483015  5.828780  0.790474   
21    683.583952  -32.576126  15.095343 -12.576780  1.707262 -1.104473   
37    355.877850   61.535566  -6.242785  -4.970090 -3.076071  1.750950   
46    783.838668  -56.826556  13.657869 -10.929661 -7.112941 -2.742609   
..           ...         ...        ...        ...       ...       ...   
499 -1099.486889  112.597421 -27.476067  -0.145937 -2.458353 -1.537728   
501   109.464701   -2.229269   3.854344  10.871600 -3.023712  2.215435   
503 -2166.185165 -108.422615  21.170655  -9.870265  4.600230 -6.029129   
509   -64.596512   50.650874 -13.205191  13.519044 -3.370923  1.640083   
512    81.753871  -65.157008  -2.878240  10.121694  4.231035 -1.561071   

            6         7         8         9        10        11        12  \
19   0.336992  0.159502 -0.013716  0.010386  0.078203 -0.036511 -0.029271   
20   0.080541  0.454472 -0.268240  0.092501  0.032368  0.122332  0.037006   
21  -0.309995 -0.328012 -0.135464 -0.232627 -0.039800  0.013665 -0.016789   
37  -0.091251 -0.511769 -0.102631  1.011803  0.024114 -0.059378 -0.000325   
46  -0.747497  0.247352 -0.345514 -0.233113 -0.080757  0.095598  0.009075   
..        ...       ...       ...       ...       ...       ...       ...   
499  1.274740 -0.224613 -0.469098 -0.102762  0.047910  0.093248 -0.100222   
501  0.365275  0.020654 -0.201790 -0.171657 -0.100881  0.175142  0.032250   
503 -3.231749 -0.385159  0.459618  0.086349  0.186573 -0.070107  0.065125   
509  2.685771 -0.600741 -0.693918 -0.225630  0.032308 -0.042296 -0.018556   
512  0.335364  0.303605 -0.151272 -0.183464  0.011138 -0.013619 -0.058982   

           13        14 diagnosis  
19  -0.039346 -0.017123         B  
20   0.000394 -0.017677         B  
21   0.007654  0.010671         B  
37   0.018064 -0.035210         B  
46  -0.027129 -0.006755         B  
..        ...       ...       ...  
499  0.029009  0.056247         M  
501 -0.029611  0.042311         M  
503  0.036807  0.019955         M  
509  0.033451  0.003069         M  
512 -0.046188  0.004539         M  

[398 rows x 16 columns]

In [39]:
cv_data_len = int(0.2*new_data.shape[0])

In [40]:
cv_data_len

113

In [41]:
training_data_len

398

In [42]:
benign_remaining_data = new_data[new_data['diagnosis']  == 'B'].iloc[training_data_len//2:]
malignant_remaining_data = new_data[new_data['diagnosis'] == 'M'].iloc[training_data_len//2:]

In [43]:
benign_remaining_data

0          1          2         3          4         5  \
360  337.662831  13.603109   7.197679 -4.373903   0.082766  0.808555   
361  279.264179  41.518148  -4.249361  3.145488  -4.728422  0.608089   
362  340.809359  20.728760  -4.097612 -1.003704  -2.691819  1.465143   
363 -204.757006  90.211725 -18.883469 -1.756263  -0.219389  1.039907   
364  240.380402  24.968074 -13.658963 -4.682545   1.017198  0.847132   
..          ...        ...        ...       ...        ...       ...   
558  125.245136  78.423433 -15.159204  6.067861  -0.348995  1.346120   
559  479.335707  -4.377873   3.076571  8.450285 -11.156618 -0.057017   
560  177.242816  43.723143  -1.611521  9.768319  -7.122694  2.436048   
561  518.011863  -1.530855  11.592324  7.646252 -17.809466  1.162060   
568  771.527622 -88.643106  23.889032 -2.547249 -14.717566 -4.418123   

            6         7         8         9        10        11        12  \
360 -1.345052  0.154547  0.339844 -0.047857  0.139427 -0.006492 -0.013628   
361  0.469150 -0.083969 -0.017369  0.010781  0.211377 -0.046522  0.030440   
362  1.022100  0.026956 -0.045440 -0.090106  0.107167 -0.001199  0.034532   
363  1.255093 -0.242152  0.245970  0.168264  0.107683 -0.018270  0.006603   
364 -0.127569  0.639383  0.113593 -0.023168  0.049693 -0.009953  0.017647   
..        ...       ...       ...       ...       ...       ...       ...   
558 -1.468684  0.112979 -0.523217 -0.060467  0.098381 -0.032695 -0.035019   
559  2.889626 -0.878398 -0.318441  0.393241 -0.032629 -0.099712 -0.072697   
560 -1.502474 -0.090413  0.056816 -0.237315  0.186363  0.023736  0.033382   
561 -0.441660 -1.117335  0.035812  1.372336 -0.019131  0.000001  0.000636   
568 -2.815752 -0.030039  0.423451 -0.301439 -0.133353  0.115105 -0.019667   

           13        14 diagnosis  
360  0.009130 -0.006040         B  
361 -0.007138  0.004174         B  
362  0.003862 -0.005173         B  
363  0.030339 -0.003954         B  
364  0.005469 -0.024220         B  
..        ...       ...       ...  
558  0.058997 -0.025474         B  
559  0.065722 -0.018011         B  
560  0.052395 -0.004542         B  
561  0.086480 -0.040917         B  
568 -0.013734  0.004134         B  

[158 rows x 16 columns]

In [44]:
remaining_data = pd.concat([benign_remaining_data,malignant_remaining_data])

In [45]:
remaining_data.shape

(171, 16)

In [46]:
cv_data = remaining_data.iloc[0:cv_data_len]
testing_data = remaining_data.iloc[cv_data_len:]

In [47]:
cv_data

0           1          2          3         4         5  \
360  337.662831   13.603109   7.197679  -4.373903  0.082766  0.808555   
361  279.264179   41.518148  -4.249361   3.145488 -4.728422  0.608089   
362  340.809359   20.728760  -4.097612  -1.003704 -2.691819  1.465143   
363 -204.757006   90.211725 -18.883469  -1.756263 -0.219389  1.039907   
364  240.380402   24.968074 -13.658963  -4.682545  1.017198  0.847132   
..          ...         ...        ...        ...       ...       ...   
504  708.652366  -46.309970  20.256051  -6.974095  5.332109 -0.887871   
505  672.591115  -40.410247  15.804085  -7.111722  3.502496  0.450757   
506  418.653294   16.975835  -4.528050  -0.495592 -1.475002  1.918475   
507  552.979663   -3.106955   3.312061  -4.842037  0.016714  0.962567   
508 -125.261547  116.510102 -26.946110 -10.025299  2.490015  2.155754   

            6         7         8         9        10        11        12  \
360 -1.345052  0.154547  0.339844 -0.047857  0.139427 -0.006492 -0.013628   
361  0.469150 -0.083969 -0.017369  0.010781  0.211377 -0.046522  0.030440   
362  1.022100  0.026956 -0.045440 -0.090106  0.107167 -0.001199  0.034532   
363  1.255093 -0.242152  0.245970  0.168264  0.107683 -0.018270  0.006603   
364 -0.127569  0.639383  0.113593 -0.023168  0.049693 -0.009953  0.017647   
..        ...       ...       ...       ...       ...       ...       ...   
504 -0.394844 -0.890593 -0.394747 -0.549510 -0.147132  0.118840  0.067029   
505  0.814044 -0.393242 -0.623021 -0.005229 -0.285082  0.110460  0.033427   
506 -0.959544  0.737403 -0.368999 -0.025598 -0.134872 -0.007528 -0.062804   
507 -0.761657  0.194564 -0.388625  0.019757  0.015741  0.038447  0.041283   
508 -0.685393  0.516865  0.105099  0.038519 -0.024173 -0.059299 -0.009121   

           13        14 diagnosis  
360  0.009130 -0.006040         B  
361 -0.007138  0.004174         B  
362  0.003862 -0.005173         B  
363  0.030339 -0.003954         B  
364  0.005469 -0.024220         B  
..        ...       ...       ...  
504  0.020695  0.058732         B  
505  0.050076  0.030077         B  
506 -0.021071 -0.004018         B  
507 -0.005783  0.001047         B  
508  0.003361 -0.004911         B  

[113 rows x 16 columns]

In [48]:
testing_data

0           1          2          3          4         5  \
510   468.335643   15.365047  -0.827115  -6.946220   3.742001  1.082143   
511    90.547058   84.702937 -14.862191  -7.320504   4.702856  0.650109   
513    13.882992   13.242216  -2.582961  -4.770083   9.141309  0.684482   
515   482.149027  -17.043363   5.320532  -3.439970  -1.866508  1.191039   
518   260.052625  -31.315042   8.068103   4.770763   5.280829  1.039662   
519   303.492556   -4.545996   5.079922  -0.364805   4.307432  0.739271   
520   681.583641  -52.401063  18.694701  -8.558976   1.882810 -1.458548   
522   520.808520    2.302135  -1.453325  -2.671834  -6.084091  0.140763   
523   196.893522   21.103080  -3.428177   2.166690   1.220961  1.014706   
524   620.561204  -48.093794  10.372840  -3.537066  -0.189877 -2.813347   
525   745.022121  -57.431691  10.220830 -11.348905  -0.520921 -3.710845   
526   192.430670   -5.308366 -14.019211   2.142277   2.523953  0.122495   
527   368.577841    4.341581 -10.468513  -7.636394   4.204844 -0.342439   
528   225.523469   66.518058  16.739762  -5.206854   8.419451  2.660303   
529   392.929018   -7.666124   0.521041  -7.169897   7.164958  0.534854   
530   401.674388  -28.114738  12.706494   3.487946  -0.257298 -1.067237   
531   407.535831  -33.116421  -2.144857   2.238526  -3.398875 -0.447141   
532   134.103392  -12.278802 -15.476284  -4.409185   4.547767  0.515747   
534   556.616798   -2.126580   1.104542  -1.503238  -3.723470 -0.246692   
537   465.866538   -8.713393   6.066910   8.904987  -5.697460  0.743754   
538   790.313242  -79.816491  24.910453  -2.353917 -16.122672 -3.674620   
539   815.980267  -74.336418  18.917243  -3.064820 -17.690207 -2.473789   
540   493.647933    3.930971   8.498568  -5.755232   2.370979  1.495655   
541    60.782512   38.560713 -15.377557  11.730357  -1.125843 -0.926569   
542    39.662072   39.814822 -11.550060   7.042010  -6.120139  0.798840   
543   276.257863   30.421930  -7.711464   9.034900 -12.832897  1.478649   
544   201.254078   39.818240  -6.634898   2.207967   0.486445  1.509547   
545   171.841169    8.356061   0.288523   3.270999  -4.816980  1.683995   
546   597.225414  -25.310300   7.039693  -7.157267  -2.547289 -0.580714   
547   623.076493  -14.523247   2.592103  -6.166315  -2.296453 -0.570320   
548   635.064042  -48.234603  14.564325  -3.864588  -6.261463 -1.500099   
549   473.472752  -56.553407  19.383860   6.817346  -6.371372 -1.771220   
550   554.764270   -9.017131  11.987428  -2.235679  -5.684196  0.425997   
551   524.660056   -6.280800   7.053336   1.563422  -6.610568  0.619216   
552   322.054342   22.374055  -3.892676   7.407059 -14.242196  1.715646   
553   704.967034  -31.301245  18.232933  -4.643734  -9.087563 -0.199432   
554   317.926338   27.369409  -6.161932   7.474182 -13.482720  1.927475   
555   622.214536  -14.274317   9.335534   4.488962 -15.673689  0.860592   
556   636.046256  -17.043600  12.995330  -5.366897  -5.245767  0.871042   
557   670.677027  -43.206959  27.182225   4.651451 -15.573118 -0.940620   
558   125.245136   78.423433 -15.159204   6.067861  -0.348995  1.346120   
559   479.335707   -4.377873   3.076571   8.450285 -11.156618 -0.057017   
560   177.242816   43.723143  -1.611521   9.768319  -7.122694  2.436048   
561   518.011863   -1.530855  11.592324   7.646252 -17.809466  1.162060   
568   771.527622  -88.643106  23.889032  -2.547249 -14.717566 -4.418123   
514   -98.355536   -4.575816  -7.637134   2.022734   0.225799  0.685657   
516  -731.367197   22.000256 -13.837862  -2.593400   0.112692  2.030727   
517  -946.295946   81.050509 -34.339797  -0.744545   3.714421 -3.170606   
521 -2127.018093  100.287669 -18.319361 -12.099332  -4.004485 -3.880847   
533  -991.378730  154.526767   4.126499  -2.917433  -2.933423  0.371844   
535 -1135.581948   77.074627 -16.040917  -5.233813  -0.406832  2.243757   
536   143.994567   57.604679 -15.071043   9.039275  -5.061848  0.264582   
562   -61.940799   35.264802 -24.064897 

In [49]:
training_data_len

398

In [50]:
training_data[training_data['diagnosis'] == 'M'].shape

(199, 16)

In [51]:
mu_hat_m = np.array(training_data[training_data['diagnosis'] == 'M'].iloc[:,0:15].mean())
sigma_hat_m = np.array(training_data[training_data['diagnosis'] == 'M'].iloc[:,0:15].cov())


In [52]:
np.linalg.det(sigma_hat_m)

np.float64(19723.27120644734)

In [53]:
mu_hat_m

array([-6.19149059e+02, -9.10604406e+00, -3.00251408e+00,  3.21867937e+00,
        6.62722209e-01, -1.49641755e-03,  1.33728677e-01, -6.56051800e-03,
        4.44266350e-02, -2.27845949e-02, -5.28254216e-02,  2.13821710e-03,
        2.13592658e-03, -4.87610367e-03,  1.12627757e-04])

In [54]:
sigma_hat_m.diagonal()

array([4.83251406e+05, 1.80244546e+04, 1.71425537e+03, 7.92821249e+01,
       4.99687724e+01, 4.96625902e+00, 2.33253962e+00, 5.72687305e-01,
       3.00085039e-01, 8.46220743e-02, 4.76165511e-02, 1.09368344e-02,
       5.88573773e-03, 3.24464641e-03, 2.37829604e-03])

In [55]:
sigma_hat_m

array([[ 4.83251406e+05,  8.37576265e+03, -6.80139734e+03,
         3.91937615e+03,  1.42781650e+03,  1.40434883e+02,
         1.42858391e+02,  5.02633310e+01,  7.03271321e+01,
        -9.73980725e+00, -3.40645517e+01, -8.13861896e-02,
         5.29094509e-01, -2.56580783e+00,  1.64154303e+00],
       [ 8.37576265e+03,  1.80244546e+04,  5.20425782e+02,
        -3.99002285e+00, -1.10489661e+02, -5.51668838e+01,
        -2.50012698e+00, -6.72820281e+00,  5.56212237e-01,
        -3.88180366e+00, -4.74513700e+00,  1.14665375e+00,
        -1.60763303e-01, -2.69180836e-01, -2.38452497e-02],
       [-6.80139734e+03,  5.20425782e+02,  1.71425537e+03,
         3.43387748e+01,  3.82365255e+01,  5.86103968e+00,
         7.74555602e+00,  7.75118427e+00, -2.04435736e-01,
         1.86529448e-01,  1.04087648e+00, -2.25587905e-01,
         5.24374493e-02,  1.05143882e-01, -2.18768048e-01],
       [ 3.91937615e+03, -3.99002285e+00,  3.43387748e+01,
         7.92821249e+01,  2.06206145e+01, -8.56543683

In [56]:
sigma_hat_m.shape

(15, 15)

In [57]:
malignant_prior = training_data[training_data['diagnosis'] == 'M'].shape[0]/training_data_len

In [58]:
malignant_prior

0.5

In [59]:
mu_hat_b = np.array(training_data[training_data["diagnosis"] == 'B'].iloc[:,0:15].mean())
sigma_hat_b = np.array(training_data[training_data["diagnosis"] == 'B'].iloc[:,0:15].cov())

In [60]:
np.linalg.det(sigma_hat_b)

np.float64(1.830445889705868e-06)

In [61]:
mu_hat_b

array([ 3.97528379e+02,  9.06204470e-01,  3.54739985e+00, -3.13352427e+00,
        3.79908894e-01,  4.33533255e-02, -2.13645508e-02, -4.14581153e-02,
       -1.31463250e-02,  1.36211788e-02,  2.10626089e-02, -1.23645051e-03,
       -1.94878048e-03, -1.52977374e-03,  1.01138045e-03])

In [62]:
sigma_hat_b.shape

(15, 15)

In [63]:
benign_prior = training_data[training_data['diagnosis'] == 'B'].shape[0]/training_data_len

In [64]:
benign_prior

0.5

In [65]:
def mock_test(data):

  inputs = np.array(data.iloc[:,0:15])

  posterior_m = s.multivariate_normal.pdf(inputs,mu_hat_m,sigma_hat_m) * malignant_prior

  posterior_b = s.multivariate_normal.pdf(inputs,mu_hat_b,sigma_hat_b) * benign_prior

  boolean_mask = posterior_m > posterior_b

  predicted_category = pd.Series(boolean_mask)

  predicted_category.replace(to_replace=[True,False],value=['M','B'],inplace=True)

  return np.array(predicted_category)

In [66]:
cv_results = mock_test(cv_data)

In [67]:
cv_results

array(['B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M'], dtype=object)

In [68]:
actual_results = np.array(cv_data['diagnosis'])
actual_results

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B'], dtype=object)

In [69]:
sigma_hat_b.diagonal()

array([3.93448586e+04, 1.18379962e+03, 1.40075464e+02, 2.47387277e+01,
       2.65583990e+01, 1.70909441e+00, 1.36650566e+00, 2.70243150e-01,
       6.55623830e-02, 9.32803276e-02, 2.61349867e-02, 6.33739713e-03,
       2.01105944e-03, 1.86785462e-03, 8.75868974e-04])

In [70]:
boolean_mask = cv_results == actual_results

In [71]:
cv_accuracy = np.count_nonzero(boolean_mask)/len(boolean_mask)

In [72]:
cv_accuracy

0.9292035398230089

In [73]:
testing_results = mock_test(testing_data)

In [74]:
testing_results

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'B',
       'M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

In [75]:
actual_results2 = np.array(testing_data['diagnosis'])
actual_results2

array(['B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M'], dtype=object)

In [76]:
boolean_mask2 = testing_results == actual_results2

In [77]:
testing_accuracy = np.count_nonzero(boolean_mask2)/len(boolean_mask2)

In [78]:
testing_accuracy

0.9827586206896551